language: php
php:
    - 5.3
    #- 5.4
env:
    - SYMFONY_VERSION=v2.0.5
    - SYMFONY_VERSION=origin/master
before_script:
    - sh -c "sudo apt-get install -y php5-intl php5-gd"
    - sh -c "psql -c 'create database test;' -U postgres;"
    - sh -c "sudo /etc/init.d/apache2 force-reload"
    - php vendor/vendors.php
