language: php
php:
    - 5.3
    - 5.4
env:
    - SYMFONY_VERSION=v2.0.6
    - SYMFONY_VERSION=origin/master
before_script:
    - sh -c "psql -c 'create database test;' -U postgres;"
    - php vendor/vendors.php
script: rake test
