language: php

php:
    - 5.3
    - 5.4

services: mongodb

env:
  - SF_VERSION="2.1.*"
  - SF_VERSION="2.2.*"

before_script:
    - pecl -q install mongo
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer require -n --no-update symfony/framework-bundle:${SF_VERSION}
    - composer update --dev

notifications:
  email: travis-ci@generation-multiple.com
