language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  - COMPOSER_OPTIONS="--prefer-source"
  - COMPOSER_OPTIONS="--prefer-source --prefer-lowest"

before_script:
    - composer update $COMPOSER_OPTIONS

notifications:
  email: false
