language: php

php:
    - 5.3
    - 5.4

before_script:
    - mongo test --eval 'db.addUser("travis", "test");'
    - ./bin/travis-mongo-installer.sh > /dev/null
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev

notifications:
  email: travis-ci@generation-multiple.com
